print("-------------Hands On 1------------------")
favFoods=['sushi', 'ribeye', 'gumbo', 'kimchi', 'kim bap', 'bi bim bap']
print("Favorite Foods: ", favFoods)
luckyNums=[14, 7, 19, 20, 1, 25]
print("Lucky Numbers: ", luckyNums)
favMovies=['Die Hard', 'Star Wars', 'Enemy of the State']
print("Favorite Movies: ", favMovies)
print("Last Food Item: ",favFoods[-1])
print("2nd, 4th, and 6th Numbers: ", luckyNums[1], luckyNums[3], luckyNums[5])
print("All firsts: ", favFoods[0], luckyNums[0], favMovies[0])
print("--------------Hands On 2-----------------")
favMovies.append("Alita: Battle Angel")
print("Add Movie: ",favMovies)
luckyNums.insert(3, 91)
print("Insert number at 3: ",luckyNums)
favFoods.insert(5, 'reuben sandwich')
print("Insert food at 5: ",favFoods)
del favFoods[5]
print("Deleted food[5]: ",favFoods)
luckyNums.pop()
print("Pop() lucky numbers: ",luckyNums)
luckyNums.pop(2)
print("Pop(2) lucky numbers: ",luckyNums)
print("--------------Hands On 3-----------------")
favMovies.sort()
print("Sorted List: ",favMovies)
favFoods.sort()
print("Sorted List: ", favFoods)
print("Temp Sorted: ", sorted(luckyNums))
print("Default Numbers: ",luckyNums)
favMovies.reverse()
print("Reverse Movies: ", favMovies)