car='subaru'
print("===============5-1=================")
print("Is car == 'subaru'? I predict True.")
print(car=='subaru')

print("\nIs car == 'audi'? I predict False.")
print(car=='audi')

n=2
s=4
name="Gary"
print("---------------True---------------")
print("Does n=(4-2)? I think True.")
print(n==(4-2))
print("Does s-n=n?")
print(s-n==n)
print("Is n+n=s?")
print(n+n==s)
print("Does n*n=s?")
print(n*n==s)
print("Spongebob's pet is Gary.")
print(name=="Gary")
print("----------------False-------------")
print("Does n=(4+2)? I think False.")
print(n==(4+2))
print("Does s+n=n?")
print(s+n==n)
print("Is n-n=s?")
print(n-n==s)
print("Does n/n=s?")
print(n/n==s)
print("Spongebob's pet is Earl.")
print(name=="Earl")
print("=================5-2==============")
car="Tesla"
print("The car is a Tesla.")
print(car=="Tesla")
print("The car is a Hyundai.")
print(car=="Hyundai")
print("The car is a tesla.")
print(car.lower()=="tesla")
print("The car is a tesla.")
print(car=="tesla")
print("5>3")
print(5>3)
print("5-2=4")
print(3!=(5-2))
hours=30
hours2=50
print("Did Jeff have overtime OR work over 80 hours in the two week pay period?")
print(hours+hours2<80 or hours>40 or hours2>40)
print("Did Jeff have overtime AND work over 80 hours in the two week pay period?")
print(hours+hours2<80 and hours>40 and hours2>40)
list1=['hockey','football','baseball']
print("Basketball is one of my favorite sports.")
print('basketball' in list1)
print("Hockey is one of my favorite sports.")
print("hockey" in list1)
print("Basketball is not one of my favorite sports.")
print('basketball' not in list1)
print("Baseball is not one of my favorite sports.")
print('baseball' not in list1)